# Generated by Django 5.2.7 on 2025-10-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_alter_booking_options_booking_added_to_queue_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancellation_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
