# Generated by Django 5.2.7 on 2025-11-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_alter_booking_cancellation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('eft', 'EFT'), ('credit', 'Credit'), ('other', 'Other')], max_length=10),
        ),
    ]
