# Generated by Django 5.2.7 on 2025-11-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0004_alter_income_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='credit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='income',
            name='credit_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
